name: pipeline
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fectch-depht: 0

    - name: Package
      run: mvn package

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: action/checkou@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribuition: 'adopt'
          package: '*.jar'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: $({ secrets.GITHUB_TOKEN })
